package kz.dvij.dvij_compose3.firebase

data class MeetingsAdsClass(
    val key: String? = null,
    val category: String? = null,
    val headline: String? = null,
    val description: String? = null,
    val price: String? = null,
    var phone: String? = null,
    var whatsapp: String? = null,
    val data: String? = null,
    val startTime: String? = null,
    val finishTime: String? = null,
    val image1: String? = null,
    val image2: String? = null,
    val image3: String? = null,
    val city: String? = null,
    val instagram: String? = null,
    val telegram: String? = null,
    val placeKey: String? = null,
    val headlinePlaceInput: String? = null,
    val addressPlaceInput: String? = null,
    val ownerKey: String? = null,
    val dateInNumber: String? = null,
    val createdTime: String? = null,
)
