package kz.dvij.dvij_compose3.firebase

data class PlacesCardClass(
    val logo: String? = null,
    val placeName: String? = null,
    val placeDescription: String? = null,
    val phone: String? = null,
    val whatsapp: String? = null,
    val telegram: String? = null,
    val instagram: String? = null,
    val category: String? = null,
    val city: String? = null,
    val address: String? = null,
    val placeKey: String? = null,
    val owner: String? = null,
    val meetingCounter: String? = null,
    val stockCounter: String? = null,
    val favCounter: String? = null,
    val viewCounter: String? = null,
    val mondayOpenTime: String? = null,
    val mondayCloseTime: String? = null,
    val tuesdayOpenTime: String? = null,
    val tuesdayCloseTime: String? = null,
    val wednesdayOpenTime: String? = null,
    val wednesdayCloseTime: String? = null,
    val thursdayOpenTime: String? = null,
    val thursdayCloseTime: String? = null,
    val fridayOpenTime: String? = null,
    val fridayCloseTime: String? = null,
    val saturdayOpenTime: String? = null,
    val saturdayCloseTime: String? = null,
    val sundayOpenTime: String? = null,
    val sundayCloseTime: String? = null,
    val createPlaceTime: String? = null
)
